default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: deploy
  password: deploy
  host: 0.0.0.0
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  database: testDeploy_production
  host: 172.17.0.2
  port: 3306

development:
  <<: *default
  database: testDeploy_development
